### ISSUE TITLE
but an image of the app in the read me file

### ISSUE THREAD

**Issue by Abdelrhman-Rayis** [Abdelrhman-Rayis/Hekama#4]

**Comment by al-rayis** [comment]
![goodp](https://cloud.githubusercontent.com/assets/12293949/20040206/4061b47c-a464-11e6-836d-d83a49ac9f3e.PNG)
![main](https://cloud.githubusercontent.com/assets/12293949/20040207/40663948-a464-11e6-9c99-a7b58506f91a.PNG)
